apiVersion: v1
kind: Service
metadata:
  name: {{ include "photobooth-app.fullname" . }}
spec:
  selector:
    app: {{ include "photobooth-app.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
  type: {{ .Values.service.type }}